# Generated by Django 5.1.2 on 2024-10-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_destination4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination2',
            name='vid',
            field=models.FileField(upload_to='videos_uploaded2'),
        ),
        migrations.AlterField(
            model_name='destination3',
            name='vid',
            field=models.FileField(upload_to='videos_uploaded3'),
        ),
        migrations.AlterField(
            model_name='destination4',
            name='vid',
            field=models.FileField(upload_to='videos_uploaded4'),
        ),
    ]
