# Generated by Django 5.1.2 on 2024-10-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_destination4_alter_destination2_vid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.FileField(upload_to='videos_uploaded')),
            ],
        ),
    ]
